### ISSUE TITLE
Contribuer au projet Geocontrib-frontend ?

### ISSUE THREAD

**Issue by f-necas** [neogeo-technologies/geocontrib#154]
Bonjour, 

Je souhaite contribuer au projet Geocontrib-frontend : https://git.neogeo.fr/geocontrib/geocontrib-frontend

Est-ce qu'il est possible de pouvoir fork le projet sur github et proposer des PRs ? 

Merci d'avance !

**Comment by m-etourneau** [comment]
Bonjour @f-necas,

Les contributions à Géocontrib se font sur notre instance Gitlab => https://git.neogeo.fr/geocontrib/geocontrib-frontend. Je vous invite à m'envoyer un mail (metourneau@neogeo.fr) afin que l'on procède à la création d'un compte qui vous permettra de faire un fork du projet et autant de PRs que vous le souhaitez !

Bien à vous
