### ISSUE TITLE
Differences with FixMyStreet solution

### ISSUE THREAD

**Issue by PanierAvide** [neogeo-technologies/geocontrib#31]
Hello,

More a question than an issue (however it could be interesting to document this) : what are the main differences with the FixmyStreet platform ( https://fixmystreet.org/ ) ? They have many similarities at first glance :
* Open-source
* Made for crowd-sourced "signalements" / geolocated features
* Highly-configurable
* Web-based UI

But I'm sure they offer different features if you look into details.

Best regards.

**Comment by bchartier** [comment]
Je vous réponds en français car ce sera plus facile.
Je ne connais pas fixmystreet.org.
GéoContrib n'est pas une solution spécifiquement conçue pour permettre de remonter des dysfonctionnements, des anomalies ou des dégradations sur le terrain.
Il s'agit d'un outil pour alimenter des bases de données de manière collaborative et contributive.
Cela s'adresse par exemple (mais pas exclusivement) à des groupes projet qui veulent constituer ou améliorer des bases de données sur un même territoire. Typiquement :
* enrichir une base de données sur des points de collecte sur le territoire d'une communauté de communes
* mettre en place un projet de plan d'adressage sur une commune
L'outil est organisé autour d'un système de commentaires ce qui facilite les échanges sur la qualité des données.
L'outil est facilement configurable par les animateurs des projets directement. Pas besoin qu'un administrateur de l'outil réalise cette configuration.

Best regards itou

**Comment by PanierAvide** [comment]
Bonjour,

Merci de ce retour, donc une approche différente et avec une ouverture thématique plus large. Une solution à tester :wink: 

Cordialement.

**Comment by bchartier** [comment]
> Bonjour,
Bonjour,
> 
> Merci de ce retour, donc une approche différente et avec une ouverture thématique plus large. Une solution à tester 😉
Si vous passez au GéoDataDays en septembre à Montpellier vous pourrez bénéficier d'une démonstration.
> 
> Cordialement.
Cordialement.
